#!/usr/bin/bash

TFILES=$(git ls | wc --lines)
RSIZE=$(du --human-readable --summarize | awk '{print $1}')
BRANCH=$(git branch --show-current)
SUMMARY=$(git diff --staged --shortstat)

# Only for Python Files
# if [ $(git diff --staged --name-only | grep py | wc --lines) -ne 0 ]
# then
#     SCORE=$(git diff --staged --name-only | grep py | xargs pylint | grep "Your code has been rated")
# fi

echo -e "\n$TFILES Files | $RSIZE | $BRANCH |$SUMMARY" >> $1
# Testing
# echo -e "$TFILES Files | $RSIZE | $BRANCH |$SUMMARY"

# END